#! /bin/bash

if [ -e /var/www/html/${PROJECT_NAME}/web/app_dev.php ]
then
  echo "Create Symfony project  nginx config"
  sed -e "s/__projectname__/${PROJECT_NAME}/g;s/__fpmhost__/${FPM_HOST}/g;s/__fpmport__/${FPM_PORT}/g" /etc/nginx/conf.d/symfony.conf.template > /etc/nginx/conf.d/default.conf
else
  echo "${PROJECT_NAME} project does not exist or does not contain app_dev.php file!"
fi
