#! /bin/bash

echo "Create nginx server files"
i=0
for dir in /var/www/html/*/
do
    if [ -e $dir/web/app_dev.php ]
    then
        dir=${dir%*/}
        dir=${dir##*/}
        echo "Create Symfony nginx server file for ${dir} project with php-fpm ${FPM_HOST}:${FPM_PORT}"

        sed -e "s/__projectname__/${dir}/g;s/__fpmhost__/${FPM_HOST}/g;s/__fpmport__/${FPM_PORT}/g" /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/${dir}.conf

        sed -i "/<li>/i <li><a href="http://local.${dir}.dev/">${dir}</a></li>" /usr/share/nginx/html/index.html
	#add hostname to hosts file
	echo "127.0.0.1 docker.${dir}.dev local.${dir}.dev" >> /etc/hosts
        i=$(($i+1))
    fi
done


echo "Create ${i} nginx server file(s)"
